spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: projectx-ui
            client-secret: changeme
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/ui-client/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8484/auth/realms/projectx/protocol/openid-connect/auth
            token-uri: http://localhost:8484/auth/realms/projectx/protocol/openid-connect/token
            user-info-uri: http://localhost:8484/auth/realms/projectx/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
    
server: 
  port: 8080
  servlet: 
    context-path: /ui-client
    
logging: 
  level: 
    org.springframework: INFO

resourceserver:
  api:
    project:
      url: http://localhost:7070/api/projects/